### ISSUE TITLE
'numpy/arrayobject.h' file not found on Mac OS 10.15.7 Catalina

### ISSUE THREAD

**Issue by suyatabe** [tnakazato/priism#13]
cmakeの後にmakeを実行しました。
![スクリーンショット 2022-01-21 16 53 41](https://user-images.githubusercontent.com/98142208/150488324-b909f05c-c76e-448e-a504-719748c88d85.png)
![スクリーンショット 2022-01-21 16 56 10](https://user-images.githubusercontent.com/98142208/150488458-91c40a6a-719c-4a4e-9dae-b076b34b9037.png)

エラーの発生：
![スクリーンショット 2022-01-21 16 50 54](https://user-images.githubusercontent.com/98142208/150487653-89227e9d-9cae-460d-8caa-e6da3d58ae29.png)

実行環境：
MacOS 10.15.7 Catalina
cmake 3.22.1
clang 13.0.0

arrayobject.hはパソコン内に４つあり、どれを呼び出そうとしているのかわかりません。
makeを成功させたいのですが、どうすればよいでしょうか？
よろしくおねがします。

**Comment by tnakazato** [comment]
お問い合わせありがとうございます。直接cmakeを実行するインストールは非推奨なので、README.mdに記載されているsetup.pyを使った方法を試していただけないでしょうか。venvで仮想環境を作成されていると思うので、その状態で

```
# クローンしたディレクトリに移動
$ cd /path/to/priism
$ python3 -m pip install -r requirements.txt
$ python3 setup.py build
$ python3 setup.py install
```

を順番に実行してみてください。

**Comment by suyatabe** [comment]
実行したところ、
![スクリーンショット 2022-01-22 14 21 45](https://user-images.githubusercontent.com/98142208/150625981-f73b91ed-9dcb-41e4-92c1-dca96a1ca56f.png)
となり、
![スクリーンショット 2022-01-22 14 24 23](https://user-images.githubusercontent.com/98142208/150626038-b7a1d37c-59a9-45ce-bef7-afa15d49247b.png)
となってしまいました。
やはり、これらのエラーはOpenMPを見つけられなかったことが原因でしょうか？
使用しているclangはこのとおりです。
![スクリーンショット 2022-01-22 14 26 53](https://user-images.githubusercontent.com/98142208/150626100-6b92126e-229a-4763-8e13-ab3004c926a9.png)

**Comment by suyatabe** [comment]
すみません
Could not find OpenMP　については呼び出すことに成功しました。パスを通し忘れていたようです。
![スクリーンショット 2022-01-22 15 33 39](https://user-images.githubusercontent.com/98142208/150627888-2113ed97-4b8c-4495-a8b6-b6f612706034.png)
エラーに変化はありませんでした。

**Comment by tnakazato** [comment]
リンカのエラーが2つ出ておりますので、それらが原因かと思われます。

* `ld: library not found for -llog4cxx`
* `ld: library not found for -lfftw3_omp`

上記について質問です。

* Log4cxxはインストールされているでしょうか？Log4cxxは依存ライブラリの一つですが、なくてもビルドできるはずなのでこのエラーが出たことにやや驚いています。
* FFTW3はインストールされていますでしょうか？
* 一旦priism以下のすべてのファイルを削除し、リポジトリのクローンからやり直しても同じエラーが出るでしょうか？

以上ご確認いただければと思います。よろしくお願いします。

**Comment by tnakazato** [comment]
リンカのエラーが2つ出ておりますので、それらが原因かと思われます。

* `ld: library not found for -llog4cxx`
* `ld: library not found for -lfftw3_omp`

上記について質問です。

* Log4cxxはインストールされているでしょうか？Log4cxxは依存ライブラリの一つですが、なくてもビルドできるはずなのでこのエラーが出たことにやや驚いています。
* FFTW3はインストールされていますでしょうか？
* 一旦priism以下のすべてのファイルを削除し、リポジトリのクローンからやり直しても同じエラーが出るでしょうか？

以上ご確認いただければと思います。よろしくお願いします。

**Comment by suyatabe** [comment]
はい、Log4cxx、FFTW3共にインストールしております。
![スクリーンショット 2022-01-25 11 42 35](https://user-images.githubusercontent.com/98142208/150901151-aeec5339-33a7-4cd3-ad39-07198ed3460a.png)

ただ、FFTW3はbrew link がうまくできていなかったのでやり直し、リポジトリのクローンからもう一度やり直したところ
![スクリーンショット 2022-01-25 11 47 59](https://user-images.githubusercontent.com/98142208/150901746-62c2ed74-a359-430a-9276-e9ed30d506f7.png)

やはりリンクエラーが出ました。

**Comment by tnakazato** [comment]
お手数おかけしてすみません。FFTW3の方はエラーが消えていますね。2つのエラーのうち1つは解決した形です。

Log4cxxはPRIISMインストールのためにインストールされたのでしょうか？もし差し支えなければ（他に使っているところがなければ）Log4cxxをアンインストールの上再度試していただけませんか？それでインストールできるようならばLog4cxxが原因と確定できますので、試していただけると非常に助かります。

**Comment by suyatabe** [comment]
log4cxxアンインストールの上で 
$python3 setup.py build
を実行しました。
![スクリーンショット 2022-01-25 16 28 19](https://user-images.githubusercontent.com/98142208/150930763-42ad0bad-7339-4f2a-a13b-f9c982a33782.png)
warningは出てきますが、make エラーやその他エラーは出ておりません。
$ python3 setup.py install
も実行してみましたが、エラーは発生していないように見えます。
importでこのようなエラーが発生しましたが、上記warningに関連している可能性はありますでしょうか？
![スクリーンショット 2022-01-25 16 48 07](https://user-images.githubusercontent.com/98142208/150933823-9ed0c158-1ea6-4e62-a7b0-66580e2a4067.png)

**Comment by tnakazato** [comment]
報告ありがとうございます。前進していると思います。PRIISMをビルド＆インストールする際に`setup.py`を実行したときのpython3と、importのために起動したpython3は同じでしょうか？

**Comment by suyatabe** [comment]
間違って違うpythonを起動していました。
インストールを実行したpython3にてimportしたところ、問題なく動きました。
ありがとうございました。

**Comment by tnakazato** [comment]
確認ありがとうございます。無事動いたという報告をいただき安心しました。お手数をおかけしました。Log4cxxの問題については調査いたします。
