### ISSUE TITLE
The result of the 'solve' run is 'number of u-v points: 0'.

### ISSUE THREAD

**Issue by suyatabe** [tnakazato/priism#16]
'solve'を実行するとnumber of u-v points: 0'となり、画像が作れませんでした。
パラメータ入力のどこを間違えたのでしょうか？

![スクリーンショット 2022-03-11 15 29 05](https://user-images.githubusercontent.com/98142208/157814680-2a73eff4-1c8c-41ca-8201-7657d925763e.png)
![スクリーンショット 2022-03-11 15 25 48](https://user-images.githubusercontent.com/98142208/157814690-abb91f25-de65-4715-bc75-1a08b63dff1f.png)

実行環境：
MacOS 10.15.7 Catalina
python3.8

よろしくお願いします

**Comment by tnakazato** [comment]
number of u-v pointsがゼロということは、MSから読み出したビジビリティに有効なデータがなかったか、もしくはselectdataに適合するデータがそもそもMSに存在しないか、のどちらかだと思われます。

mg0414_cal2_chans.msのlistobsの出力が調査の助けになると思います。こちらに添付していただくことは可能でしょうか？

**Comment by suyatabe** [comment]
mg0414_cal_chanのtxtファイルを添付しました。
[mg0414_cal_chan2.listobs.txt](https://github.com/tnakazato/priism/files/8229727/mg0414_cal_chan2.listobs.txt)

mg0414_cal2_chan2は下に添付しましたデータのチャンネルを１個にしたものになります。
[mg0414.cal2.listobs.txt](https://github.com/tnakazato/priism/files/8229735/mg0414.cal2.listobs.txt)

**Comment by tnakazato** [comment]
添付ありがとうございます。データは問題なさそうです。

最初のレポートにあるスクリーンショットで、`worker.readvis()`が抜けているようです。`worker.defineimage`のあと、`worker.solve`を実行する前に`worker.readvis`を実行してみていただけますか？

なお、`solve`までの手順はcvrun.ipynbで確認できます。

https://github.com/tnakazato/priism/blob/main/cvrun.ipynb

**Comment by suyatabe** [comment]
写真では抜けていますが実行はしてあります。
添付し忘れていました申し訳ありません。
![スクリーンショット 2022-03-11 16 41 12](https://user-images.githubusercontent.com/98142208/157823947-69712303-77df-43c6-86b0-f3c678de15a1.png)

**Comment by tnakazato** [comment]
そうでしたか。

では、`readvis`実行後に、以下を実行して出力を共有していただけませんか？

```
print(worker.working_set.rdata)
print(worker.working_set.idata)
print(worker.working_set.weight)
```

お手数おかけしてすみません。よろしくお願いします。

**Comment by suyatabe** [comment]
readvisの後に実行してみました。

![スクリーンショット 2022-03-14 12 48 59](https://user-images.githubusercontent.com/98142208/158101690-dad55e99-1a0b-448d-abcd-e48524ca3283.png)

お手間をとらせてしまい申し訳ありません。

**Comment by tnakazato** [comment]
スクリーンショットありがとうございます。 `RuntimeWarning: invaliid value encountered in double_scalars` が気になりますね。weight値が正しく読み込めていないのかもしれません。すみませんが、下記を実行して出力を送っていただけますか？

```
from casatools import table
tb = table()
tb.open('mg0414_cal2_chans.ms')
colnames = tb.colnames()
print(f'column names: {colnames}')
sel = tb.query('DATA_DESC_ID==0 && FIELD_ID==0')
if 'WEIGHT_SPECTRUM' in colnames and sel.iscelldefined('WEIGHT_SPECTRUM', 0):
    print('WEIGHT_SPECTRUM exists')
    print(sel.getcell('WEIGHT_SPECTRUM'), 0)
else:
    print('WEIGHT_SPECTRUM is not defined')

if 'WEIGHT' in colnames and sel.iscelldefined('WEIGHT', 0):
    print('WEIGHT exists')
    print(sel.getcell('WEIGHT', 0))
else:
    print('WEIGHT is not defined')

sel.close()
tb.close()
```

**Comment by suyatabe** [comment]
実行したところWEIGHT is not defined となっておりweight値が読み込めていなさそうです。
tb.open でTable mg0414_cal2_chan.ms does not exist　と出ているのですが、この部分が原因でしょうか？


![スクリーンショット 2022-03-14 13 45 10](https://user-images.githubusercontent.com/98142208/158106476-6b997ab4-f5d3-4806-9bd6-a9fc82875aa5.png)

**Comment by tnakazato** [comment]
そうですね、指定したファイルが存在しないことが原因と考えられます。mg0414_cal2_chan.msの部分をお手元のMS名と読み替えて実行していただけますか？

**Comment by suyatabe** [comment]
元のデータを入れて実行してみたところ以下のようになりました。

![スクリーンショット 2022-03-14 14 19 41](https://user-images.githubusercontent.com/98142208/158109528-5f2d3643-160e-4bd8-9be3-575a0813a752.png)

**Comment by tnakazato** [comment]
ありがとうございます。最初に問題をレポートしていただいた時のMS名と今回のMS名は異なるようですが、これら2つのMSはどのような関係にあるのか、教えていただけますか？

また、今回検証に使っていただいたデータ `mg0414uv.ms.org.cal2` でPRIISMを実行した場合も `mg0414_cal2_chan.ms` と同様のエラーが起きるでしょうか？

よろしくお願いします。

**Comment by suyatabe** [comment]
mg0414_cal2_chan.msはmg0414uv.ms.org.cal2のチャンネルをmstransformで チャンネル数を１つにしたものです。
mg0414uv.ms.org.cal2でも同様にu-v points が０になります。
![スクリーンショット 2022-03-14 14 57 45](https://user-images.githubusercontent.com/98142208/158113598-580da658-4e3a-456a-a2f3-57e13aa5cc33.png)

**Comment by tnakazato** [comment]
mg0414_cal2_chan.msでも下記を実行していただくことは可能でしょうか？

```
from casatools import table
tb = table()
tb.open('mg0414_cal2_chans.ms')
colnames = tb.colnames()
print(f'column names: {colnames}')
sel = tb.query('DATA_DESC_ID==0 && FIELD_ID==0')
if 'WEIGHT_SPECTRUM' in colnames and sel.iscelldefined('WEIGHT_SPECTRUM', 0):
    print('WEIGHT_SPECTRUM exists')
    print(sel.getcell('WEIGHT_SPECTRUM'), 0)
else:
    print('WEIGHT_SPECTRUM is not defined')

if 'WEIGHT' in colnames and sel.iscelldefined('WEIGHT', 0):
    print('WEIGHT exists')
    print(sel.getcell('WEIGHT', 0))
else:
    print('WEIGHT is not defined')

sel.close()
tb.close()
```

お手数おかけします。

**Comment by suyatabe** [comment]
実行してみました。
mg0414_cal2_chan.ms ではやはりTable does not exist　となりました。
![スクリーンショット 2022-03-14 15 07 57](https://user-images.githubusercontent.com/98142208/158114657-80e9735c-1308-4d06-92a2-19a5dad6051b.png)

**Comment by tnakazato** [comment]
承知しました。mg0414_cal2_chan.ms は削除したということでしょうか？

**Comment by suyatabe** [comment]
いえ、mg0414_cal2_chan.msは削除はしていません。
ただmstransformのやり方が間違っていたのかもしれません。
設定できるチャンネル数は１つだけということなので、mstransformでmg0414uv.ms.org.cal2の128個あったチャンネルを無理やり１つにまとめてみたのですが、やはり無理があったかのもしれません。

**Comment by tnakazato** [comment]
いえ、元のデータ`mg0414uv.ms.org.cal2`でもPRIISMの問題は再現するので、mstransform以外に何か原因があるのかもしれません。`mg0414_cal2_chan.ms`は削除していないとのことですが、だとするとなぜ`mg0414_cal2_chan.ms`で上記のスクリプトがエラーになってしまうのでしょう。MS名に間違いがないか、もう一度確認していただけませんか？

**Comment by tnakazato** [comment]
こちらこそすみません。おそらくPRIISMのバグだろうと思うのですが、今のところ確証はありません。

試しにdefineimageのところで`width=-1`に設定して再度PRIISMのイメージングを試してみていただけますか？

**Comment by suyatabe** [comment]
実行してみました。
u-v points 0　となり、まっさらな画像になりました。

![スクリーンショット 2022-03-15 13 52 45](https://user-images.githubusercontent.com/98142208/158308927-6262ea6d-1577-4e9f-896a-5394fb018e9b.png)

**Comment by tnakazato** [comment]
いろいろ試していただいてありがとうございます。ちなみに今扱っているデータはALMAの公開データでしょうか？こちらに何らかの方法でデータを提供してくださることは可能でしょうか？データをいただければ実際にこちらで詳しい調査ができると思います。

**Comment by suyatabe** [comment]
使用しているのはMG0414＋0534を対象としたALMA望遠鏡による340GHzでの観測(cycle2:2015,6/13,8/14)データをセルフキャリブレーションしたものになります。私はこのセルフキャリブレーションしたデータを井上開輝先生にいただいて解析しておりました。
このデータは50GBほどあるのですが、どのようにお渡しすればよいでしょうか？

**Comment by tnakazato** [comment]
こちらにデータを提供いただくことは可能なのですね（もし確信がなければ井上開輝先生に確認をお願いします）。

`mg0414_cal2_chan.ms`はチャンネルを切り出してサイズを小さくしたものだと思いますが、それでも50GBということでしょうか？その場合は特定のスキャンを取り出すなどしてさらにデータサイズを小さくしてからデータの共有方法を相談させていただく形にさせていただければと思います。すみませんが確認お願いします。

**Comment by suyatabe** [comment]
はい、井上先生はデータを提供しても構わないと言ってくださいました。
すみません、違うデータを見ていたようです。mg0414_cal2_chan.ms　は2.18GBでした。

**Comment by tnakazato** [comment]
確認ありがとうございます。では、お手数ですがmstransformでmg0414_cal2_chan.msからスキャン13, 37, 61を取り出したMSを作成していただき、データサイズを確認していただけますか？コマンドは以下で良いのではないかと思います。

```
mstransform(vis='mg0414_cal2_chan.ms', outputvis='mg0414_cal2_chan_scan.ms', scan='13,37,61')
```

**Comment by suyatabe** [comment]
エラーが出てしまいました。

![スクリーンショット 2022-03-16 14 30 03](https://user-images.githubusercontent.com/98142208/158522946-e21c60f3-e3bd-4b84-9bf0-7be5550d4691.png)

**Comment by tnakazato** [comment]
```
rm -rf mg0414_cal2_chan_scan.ms
mstransform(vis='mg0414_cal2_chan.ms', outputvis='mg0414_cal2_chan_scan.ms', scan='13,37,61', datacolumn='data')
```

ではいかがでしょうか？

**Comment by suyatabe** [comment]
1.98GBになりました。

**Comment by tnakazato** [comment]
ありがとうございます。あまりサイズが変わりませんね。だとするとスキャンを取り出す前の`mg0414_cal2_chan.ms`をご提供いただく方向で検討したいと思います。すみませんがMSのサイズ内訳を送っていただけると助かります。具体的には、以下の出力をいただけると助かります。

```
du -sh mg0414_cal2_chan.ms/*
```

**Comment by suyatabe** [comment]
以下の通りでした。

![スクリーンショット 2022-03-16 15 41 08](https://user-images.githubusercontent.com/98142208/158531507-4ab8aaa4-1738-49bd-a422-ba94a83ae517.png)

**Comment by tnakazato** [comment]
ありがとうございます。POINTINGテーブルが大きいようなので、POINTINGテーブルを除外しましょう。またASDM関連も不要なので、これら以外のファイルをいただけると助かります。

```
tar zcvf data.tgz --exclude=*/POINTING* --exclude=*/ASDM* mg0414_cal2_chan.ms
```

を実行して、`data.tgz`のサイズはどの程度になりますでしょうか？

**Comment by tnakazato** [comment]
> 636.8MBになりました

まだ大きいので、スキャンを抽出した`mg0414_cal2_chan_scan.ms`の方を試してみましょうか。

```
tar zcvf data2.tgz --exclude=*/POINTING* --exclude=*/ASDM* mg0414_cal2_chan_scan.ms
```

を実行して、`data2.tgz`のサイズはどの程度になりますでしょうか？

**Comment by suyatabe** [comment]
519.7MBです

**Comment by tnakazato** [comment]
おかしいですね。`mg0414_cal2_chan_scan.ms`は全体のサイズが1.98GBで、POINTINGが1.8GBなので、圧縮しなくてもサイズは200MB弱になるはずなのですが。

```
tar ztvf data2.tgz | grep -E "(POINTING|ASDM)"
```

の出力はどうなりますか？

**Comment by suyatabe** [comment]
もう1度やり直したところ28.9MBになりました。

**Comment by tnakazato** [comment]
ありがとうございます。メールに添付できるサイズになったと思うので、お手数ですが作成したファイル（`data.tgz`か`data2.tgz`のどちらかだと思いますが）をメールで takeshi.nakazato@nao.ac.jp 宛てに送っていただけますか？

よろしくお願いします。

**Comment by suyatabe** [comment]
Googleメールに添付できるファイルの上限が25MBまでなので、Googleドライブに共有するというう形で送付させていただいてもよろしいでしょうか？
メールにはファイルをダウンロードするためのリンクが貼られることになります。

**Comment by tnakazato** [comment]
はい、それで大丈夫です。ありがとうございます！

**Comment by tnakazato** [comment]
調査が大変遅くなり申しわけありません。データの詳細を調べたところ、いただいたデータの全てが無効であることがわかりました。今回共有していただいたデータは一部を切り出したものですが、全体的にデータが無効になっているのかもしれません。（すでにクローズされてしまったのでいまさらかもしれませんが）もし可能でしたら以下を試してみていただけないでしょうか？

```
from casatasks import flagdata
summary = flagdata(vis='mg0414_cal2_chan.ms', mode='summary')
print(summary['spw'])
```

`{'0': {'flagged': 693036.0, 'total': 693036.0}}` のような出力が得られると思います。 `'total'` と `'flagged'` の数値が同じであれば、全データが無効であるということになります。mstransformにより平均操作を行なって1チャンネルのデータとしたとのことですので、以下のような原因が考えられます。

* 平均操作の中で、何らかの理由でデータが無効化されてしまった
* 平均前のデータで、すでにデータが無効化されていた
    * 例えばcalibrationの途中で無効化された（解が見つからなかったなど）
    * あるいは平均操作の対象チャンネルがもともと無効だった

対応策としては、

* mstransformのログを確認してみる: 平均操作が原因なら何らかの問題がログに報告されているかもしれません
* mstransformで平均操作のパラメータを変えてみる: 特定のチャンネルを切り出して平均しているならチャンネル範囲を変えてみる、など
* mstransformの使い方を変えてみる: 平均操作をする代わりに、特定のチャンネルだけを抜き出してみる

などが考えられます。もし継続調査されるようでしたらサポートいたしますので、このチケットをオープンしてコメントをいただければと思います。よろしくお願いします。

**Comment by suyatabe** [comment]
返信がかなり遅くなってしまい申し訳ありません。就職し新しい環境になれるのに忙しく、メールの確認ができていませんでした。申し訳ありません。
データの件ですが、もう私は研究室のパソコンに触れることができません。また、しばらくの間は個人的な活動もできそうにありません。そのため、もし差し支えなければ私から井上開輝教授、またはその研究室の学生に連絡をしてこの調査を引き継いでもらえるよう依頼しますがいかがでしょうか?

返事が遅くなりましたこと重ねてお詫びいたします。申し訳ありませんでした。

2022年4月1日(金) 17:20 tnakazato ***@***.***>:
