### ISSUE TITLE
Runtime Error using PRIISM ver 0.11.2

### ISSUE THREAD

**Issue by shoshiay** [tnakazato/priism#35]
Runtime Error was displayed during analysis using PRIISM ver 0.11.2.
There is a problem with the MS file.
How to deal with the problem?

**Comment by tnakazato** [comment]
Thanks @shoshiay for problem report. I've pushed possible fix. Could you test [improve-restfreqs-handling](https://github.com/tnakazato/priism/tree/improve-restfreqs-handling) branch?

```shell
cd priism
git checkout improve-restfreqs-handling
python3 setup.py build [please-add-your-build-options]
python3 setup.py install 
```

**Comment by shoshiay** [comment]
set -eu
### 
PRIISM_VERSION=0.11.2
PRIISM_REPO=https://github.com/tnakazato/priism

export PATH=/lfs05/shoshiay/casa/casa-6.1.0-118/bin:$PATH

which python3

cd priism-priism-$PRIISM_VERSION


git checkout improve-restfreqs-handlig

python3 setup.py build --use-intel-compiler=yes --python-library=""

python3 setup.py install

**Comment by shoshiay** [comment]
Thanks @tnakazato for solution reply.
As per your advice, I created and executed the following code, but it did not work.
After running it, I got a message "fatal: Not a git repository (or any parent up to mount point /lfs05) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)." was displayed.

**Comment by tnakazato** [comment]
OK. Then, could you download the source code from the link below?

https://github.com/tnakazato/priism/archive/refs/heads/improve-restfreqs-handling.zip

Please unzip and build it.

**Comment by shoshiay** [comment]
This problem has been solved.
Thank you for the long hours of support.
