### ISSUE TITLE
Fix the version of sparseimaging in CMakeLists.txt

### ISSUE THREAD

**Issue by astropenguin** [tnakazato/priism#5]
It seems that the version (i.e., tag or commit ID) of `ikeda46/sparseimaging` is not specified in `CMakeLists.txt`,
which may not reproduce the exact environment depending on when PRIISM is built by an user.

So I would like to propose to use an URL which contains the version information like:
https://github.com/ikeda46/sparseimaging/archive/7afb0543acabc97dc31c9707b221feb27f34af66.zip

If I misunderstand the build process, please ignore this issue.

**Comment by tnakazato** [comment]
Thank you for the report. You are right. PRIISM refers HEAD of sparseimaging repository, which can vary with time. I agree with you that this is not desirable behavior. The way you suggested would be one of the solution. On the other hand, submodule reference would also solve the problem. Although I prefer the latter approach, I'm not sure submodule reference is included in archive (zip/tar.gz) distribution. In any case, I will fix the issue as soon as possible.

**Comment by tnakazato** [comment]
I've created pull request #6 for the issue reported here. @astropenguin, could you review #6 and let me know if it solves your concern? Thank you for your cooperation.

**Comment by astropenguin** [comment]
Dear @tnakazato, thank you for updating the code. I checked it and left a comment in #6.

**Comment by tnakazato** [comment]
@astropenguin, thank you for the verification. I've merged the pull request.
