### ISSUE TITLE
Lazy import of NumPy in setup.py

### ISSUE THREAD

**Issue by astropenguin** [tnakazato/priism#7]
NumPy is imported in the global of `setup.py`, which raises `ModuleNotFoundError` when `setup.py` is run in a newly created (virtual) environment. To avoid this, I would like to propose to use a lazy import of NumPy within the specific method:

```python
def finalize_options(self):
    import numpy
    ...
```

and to add the `setup_requires` option so that NumPy is installed before a build process.

```python
setup(
    setup_requires=['numpy'],
    ...
)
```

**Comment by tnakazato** [comment]
Hi @astropenguin, 

Thank you for the suggestion and the pull request. Although installation instruction recommends to install numpy by running 
```
python3 -m pip install -r requirements.txt
``` 
before executing setup.py, I will review your pull request.

**Comment by astropenguin** [comment]
Dear @tnakazato, I am sorry for not checking `requirements.txt`. If NumPy is one of the dependencies of `casatools` or `casatasks`, then this issue is already solved. If so, please feel free to close the issue.

**Comment by tnakazato** [comment]
@astropenguin, `casatools` depends on numpy so PRIISM implicitly depends on numpy. However, it is true that dependency to numpy is not clearly stated. Any improvement should be necessary. Let me keep those issues open and please give me a time to think how to improve the situation. Thanks.
